SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE LIKE '%30%'
WHERE C.CAR_ID NOT IN(SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE > '2022-11-01' AND START_DATE <= '2022-11-30')
    AND C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 >= 500000
        AND C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 < 2000000
        AND C.CAR_TYPE IN('세단', 'SUV')
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;