SELECT C.CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR AS C
WHERE C.CAR_ID IN (SELECT CAR_ID AS ID
                    FROM CAR_RENTAL_COMPANY_CAR
                     WHERE OPTIONS LIKE '%가죽시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%통풍시트%')
GROUP BY C.CAR_TYPE
ORDER BY C.CAR_TYPE;