SELECT A.CAR_ID,
                    CASE 
                    WHEN B.ID IS NULL THEN '대여 가능'
                    ELSE '대여중'
                    END
AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT JOIN (SELECT C.CAR_ID AS ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
        WHERE '2022-10-16' BETWEEN C.START_DATE AND C.END_DATE) AS B ON A.CAR_ID = B.ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC;