SELECT F.PRODUCT_ID, F.PRODUCT_NAME, (F.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS F
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
        FROM FOOD_ORDER 
        WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '5'
        GROUP BY PRODUCT_ID) AS O
    ON F.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID;