SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
JOIN (SELECT S.CODE 
        FROM SKILLCODES AS S
        WHERE S.CATEGORY = 'Front End') AS K
        ON D.SKILL_CODE & K.CODE = K.CODE
ORDER BY D.ID;