SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        ABS(B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV,
        A.ID
FROM ECOLI_DATA AS A
LEFT JOIN (SELECT (MAX(SIZE_OF_COLONY)) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
        ON B.YEAR = YEAR(A.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;

