SELECT B.ID, C.FISH_NAME, C.MAX_SIZE AS LENGTH
FROM FISH_INFO AS B
JOIN (SELECT A.FISH_TYPE AS FISH_TYPE, N.FISH_NAME AS FISH_NAME, A.ML AS MAX_SIZE
        FROM FISH_NAME_INFO AS N
            JOIN (SELECT I.FISH_TYPE , MAX(I.LENGTH) AS ML
                    FROM FISH_INFO AS I
                    GROUP BY I.FISH_TYPE) AS A
                    ON N.FISH_TYPE = A.FISH_TYPE) AS C
    ON B.LENGTH = C.MAX_SIZE AND B.FISH_TYPE = C.FISH_TYPE
ORDER BY B.ID;



