
SELECT G.SCORE AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO) AS G
        ON G.EMP_NO = E.EMP_NO
ORDER BY G.SCORE DESC LIMIT 1;