SELECT A.CATEGORY, A.PRICE AS MAX_PRICE , A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A
WHERE (A.CATEGORY, A.PRICE) IN (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
            FROM FOOD_PRODUCT
            WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
            GROUP BY CATEGORY
)
ORDER BY A.PRICE DESC;

