# SELECT 
#         b.BOOK_ID as BOOK_ID ,
#         a.AUTHOR_NAME as AUTHOR_NAME,
#         date_format(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
# FROM BOOK b
# LEFT JOIN AUTHOR a ON b.AUTHOR_ID = A.AUTHOR_ID
#     WHERE b.CATEGORY = '경제'
# ORDER BY b.PUBLISHED_DATE ASC;


SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE 
FROM BOOK AS B
INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE;












